spring:
  data:
    source:
      url: jdbc:mysql://192.168.50.116:3306/test_s??characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: ysten123
      driver-class-name: com.mysql.jdbc.Driver

data:
  source:
    pool:
      connectionTimeout: 20000
      idleTimeout: 200
      initialSize: 20
      maxActive: 200
      minIdle: 10
      maxIdle: 20
      maxWait: 2000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      testOnBorrow: false
      testWhileIdle: true
      validationQuery: SELECT 1
      removeAbandoned: true
      removeAbandonedTimeout: 1800

spring:
  jpa:
    database: MYSQL
    show-sql: true
    generate-ddl: true
    ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        use-new-id-generator-mappings: true
        enable_lazy_load_no_trans: true
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl